knp_snappy:
    temporary_folder: '%kernel.cache_dir%/snappy'
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            disable_smart_shrinking: true
            margin-left: 0mm
            margin-right: 0mm
            margin-bottom: 0mm
            margin-top: 0mm
