version: '3'
services:
  php:
    build: docker/.
    working_dir: /app
    ports:
      - "8000:8000"
    entrypoint: docker/entrypoint_php.sh
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - db

  php-cli:
    build: docker/.
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - db

  composer:
    image: prooph/composer:7.3
    volumes:
      - .:/app

  client:
    image: node:10
    working_dir: /app
    entrypoint: docker/entrypoint_client.sh
    volumes:
      - .:/app
    depends_on:
      - php

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myprofile
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myprofile
    ports:
      - 5432
