version: '3.8'
services:
  web:
    image: nginx:1.17
    volumes:
    - ./:/app
    - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8000:80
    links:
      - php

  php:
    image: eerison/myprofile:dev
    working_dir: /app
    env_file:
      - .docker/common.env
    volumes:
      - ./:/app
    links:
      - db

  composer:
    image: prooph/composer:7.3
    volumes:
      - .:/app

  client:
    image: node:10
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - php

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myprofile
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myprofile
    volumes:
      - .docker/database/data:/var/lib/postgresql/data
    ports:
      - 5432
