version: '3'
services:
  php:
    build: docker/.
    working_dir: /app
    ports:
    - "8000:8000"
    entrypoint: docker/entrypoint.sh
    env_file:
      - .env
    volumes:
    - .:/app
    links:
    - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myprofile
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myprofile