app_profile:
    path:   /{username}/{_locale}
    defaults: {_controller: AppBundle:Default:profile, _locale: en }
    requirements:
        _locale: "en|pt_br"

app_send_contact:
    path:   /{username}/{_locale}/send_contact
    defaults: {_controller: AppBundle:Default:sendContact, _locale: en}
    requirements:
        _locale: "en|pt_br"

app_homepage:
    path:   /{_locale}
    defaults: {_controller: AppBundle:Default:index, _locale: en}
    requirements:
        _locale: "en|pt_br"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    defaults: {_locale: en}
    requirements:
            _locale: "en|pt_br"