app_skill:
    resource: "@AppBundle/Controller/SkillController.php"
    type:     annotation

app_experience:
    resource: "@AppBundle/Controller/ExperienceController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_education:
    resource: "@AppBundle/Controller/EducationController.php"
    type:     annotation

app_user_social_networking:
    resource: "@AppBundle/Controller/UserSocialNetworkingController.php"
    type:     annotation

app_social_networking:
    resource: "@AppBundle/Controller/SocialNetworkingController.php"
    type:     annotation

app_profile:
    path:   /{username}/{_locale}
    defaults: {_controller: AppBundle:Default:profile, _locale: pt_br }
    requirements:
        _locale: "en|pt_br"

app_send_contact:
    path:   /{username}/{_locale}/send_contact
    defaults: {_controller: AppBundle:Default:sendContact, _locale: pt_br}
    requirements:
        _locale: "en|pt_br"

app_homepage:
    path:   /{_locale}
    defaults: {_controller: AppBundle:Default:index, _locale: pt_br}
    requirements:
        _locale: "en|pt_br"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    defaults: {_locale: pt_br}
    requirements:
            _locale: "en|pt_br"