app_certification:
    resource: "@AppBundle/Controller/CertificationController.php"
    type:     annotation

app_skill:
    resource: "@AppBundle/Controller/SkillController.php"
    type:     annotation

app_experience:
    resource: "@AppBundle/Controller/ExperienceController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_education:
    resource: "@AppBundle/Controller/EducationController.php"
    type:     annotation

app_user_social_networking:
    resource: "@AppBundle/Controller/UserSocialNetworkingController.php"
    type:     annotation

app_social_networking:
    resource: "@AppBundle/Controller/SocialNetworkingController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    defaults: {_locale: pt_BR}
    requirements:
            _locale: "en|pt_BR"

_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error