version: 2.1

jobs:
  build:
    docker:
      - image: prooph/composer:7.3
        environment:
          APP_ENV: test
          DATABASE_URL: ''
          BUCKET_DNS: ''
          BUCKET_NAME: ''
          CDN_DNS: ''
          APP_SECRET: f7959631cf78a0283382a84670d55b53
          SENTRY_DSN: ''
          TRANSLOADIT_KEY: ''
          TRANSLOADIT_SECRET: ''
          TRANSLOADIT_TEMPLATE_ID_CURRICULUM: ''
          TRANSLOADIT_TEMPLATE_ID_IMAGE_PROFILE: ''
          TRANSLOADIT_TEMPLATE_ID_IMAGE_BACKGROUND: ''
          TRANSLOADIT_CREDENTIALS: ''
          TRANSLOADIT_DELIVERY: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.lock" }}
            - deps-
      - run: pwd
      - run: ls -l
      - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader

  test:
    docker:
      - image: circleci/php:7.3-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.lock" }}
            - deps-
      - run: bin/phpunit


workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build