version: 2.1

jobs:
  test:
    docker:
      - image: eerison/myprofile
        environment:
          APP_ENV: test
          DATABASE_URL: 'postgres://root:123456@localhost:5432/myprofile_test'
          BUCKET_DNS: ''
          BUCKET_NAME: ''
          CDN_DNS: ''
          APP_SECRET: f7959631cf78a0283382a84670d55b53
          SENTRY_DSN: ''
          TRANSLOADIT_KEY: ''
          TRANSLOADIT_SECRET: ''
          TRANSLOADIT_TEMPLATE_ID_CURRICULUM: ''
          TRANSLOADIT_TEMPLATE_ID_IMAGE_PROFILE: ''
          TRANSLOADIT_TEMPLATE_ID_IMAGE_BACKGROUND: ''
          TRANSLOADIT_CREDENTIALS: ''
          TRANSLOADIT_DELIVERY: 0
      - image: postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123456
    steps:
      - checkout
      - run: pwd
      - run: ls -l
      - run: make init
      - run: make test

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test